import {Store} from './store';

export const Ldlc: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.stock',
      text: ['stock'],
    },
    maxPrice: {
      container: '.price .price',
      euroFormat: true,
    },
    outOfStock: {
      container: '.stock',
      text: ['rupture'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00317660.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408700.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408676.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408873.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408789.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408872.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408790.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408776.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408702.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408672.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408704.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408673.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00422761.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408742.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408933.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408449.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408692.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408777.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408677.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408740.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00423472.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408741.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408779.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408695.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408743.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408741.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408683.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060',
      url: 'https://www.ldlc.com/fiche/PB00408696.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00398042.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394586.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394608.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394053.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394434.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394607.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394373.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00400751.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394602.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394375.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394343.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394379.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394357.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394060.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394507.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00398936.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00393739.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00398937.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394595.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394589.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394436.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394596.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394363.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394590.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394600.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00428443.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00408782.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00395231.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394604.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00405704.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394150.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00405821.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394365.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3060ti',
      url: 'https://www.ldlc.com/fiche/PB00394151.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00408869.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386928.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386030.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00383541.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385466.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00400752.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384198.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386014.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385126.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00383549.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386927.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385663.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384225.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385132.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00408781.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00393364.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384189.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00398664.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386926.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00408780.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385043.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385046.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386925.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00393363.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385465.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385462.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00384232.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385045.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385463.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385127.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386907.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00401469.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385128.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386904.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385048.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00395874.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385131.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00391681.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385129.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00386023.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00385044.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3070',
      url: 'https://www.ldlc.com/fiche/PB00401655.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369303.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369299.html',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00368574.html',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00368968.html',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369072.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00376208.html',
    },
    {
      brand: 'inno3d',
      model: 'twin x2',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368690.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369094.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369150.html',
    },
    {
      brand: 'evga',
      model: 'xc3 black',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369298.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386334.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00396037.html',
    },
    {
      brand: 'zotac',
      model: 'amp holo',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375625.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368844.html',
    },
    {
      brand: 'msi',
      model: 'ventus 2x oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368506.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00390466.html',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368789.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398370.html',
    },
    {
      brand: 'msi',
      model: 'suprim x',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391682.html',
    },
    {
      brand: 'gigabyte',
      model: 'vision oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00376207.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368691.html',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369158.html',
    },
    {
      brand: 'evga',
      model: 'xc3',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369268.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill frostbite',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00391624.html',
    },
    {
      brand: 'evga',
      model: 'ftw3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398046.html',
    },
    {
      brand: 'kfa2',
      model: 'sg',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368931.html',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375448.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375431.html',
    },
    {
      brand: 'evga',
      model: 'ftw3',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00369265.html',
    },
    {
      brand: 'gainward',
      model: 'phantom gs',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00390727.html',
    },
    {
      brand: 'evga',
      model: 'xc3 ultra hybrid',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398045.html',
    },
    {
      brand: 'inno3d',
      model: 'ichill x4',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368692.html',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00368579.html',
    },
    {
      brand: 'zotac',
      model: 'trinity oc',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00375644.html',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00385535.html',
    },
    {
      brand: 'palit',
      model: 'gamerock',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00386332.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3080',
      url: 'https://www.ldlc.com/fr-be/fiche/PB00398373.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00400753.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3080',
      url: 'https://www.ldlc.com/fiche/PB00423532.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00390227.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370250.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371133.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391621.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374629.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371132.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374628.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370913.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374631.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370057.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398039.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374912.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374914.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374838.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00369842.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00401472.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371131.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398037.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374606.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374614.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00371280.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370065.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374837.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398044.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00386908.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00370903.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391541.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00390729.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00398364.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00400756.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391683.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00374911.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00391625.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00369849.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00389189.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00390730.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00376302.html',
    },
    {
      brand: 'gigabyte',
      model: 'aorus xtreme waterforce wb',
      series: '3090',
      url: 'https://www.ldlc.com/fiche/PB00407277.html',
    },
    {
      brand: 'asrock',
      model: 'amd reference',
      series: 'rx6700xt',
      url: 'https://www.ldlc.com/fiche/PB00412453.html',
    },
  ],
  name: 'ldlc',
};
